### ISSUE TITLE
Crash when .sav.bak files are present in the save directory

### ISSUE THREAD

**Issue by synogen** [synogen/ftlautosave#17]
Caused by: java.lang.NumberFormatException: For input string: "bak"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Long.parseLong(Unknown Source)
        at java.lang.Long.valueOf(Unknown Source)
        at org.synogen.ftlautosave.Util.getTimestamp(Util.java:8)
        at org.synogen.ftlautosave.ui.MainController.refreshSavesList(MainController.java:91)
        at org.synogen.ftlautosave.ui.MainController.initialize(MainController.java:56)

**Comment by synogen** [comment]
Fixed.
